### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [schober2/tc359#1]
It looks like this repo isn't _exactly_ what's staged [on Heroku](https://warm-badlands-7934.herokuapp.com/). This isn't a strike - I think just a misunderstanding. Can you try updating the project with a GitHub repo that is _just_ the `ruby-getting-started` folder. You can do this by opening up the terminal, `cd`ing into that folder, then the following commands should be helpful to create a new GitHub repo.

``` bash
git remote remove origin # not normally necessary, but is necessary whenever cloning someone else's repo, like we just did
gem install hub          # installs the hub gem - only necessary once
hub create heroku-test   # creates a repo called heroku-test and sets it as origin
git push origin master   # pushes our master branch to origin, which is pointing to the GitHub repo we just created
```

Please don't hesitate if you have any questions!

**Comment by schober2** [comment]
I think it should be all set, I did have to do a remote set-url command though, so that's probably why it wasn't working right before, I'm not sure if that's normal or just some residual nastiness from previous git configurations. It should be available now at https://github.com/schober2/heroku-test.

**Comment by chrisvfritz** [comment]
Looks fantastic! Problem resolved. :smile:
